---
- name: install pxe packages
  yum:
    pkg: "{{ pxe_packages }}"
    state: installed
  become: true

- name: initial directories
  file:
    path: "{{ item }}"
    state: directory
    owner: admin
    group: admin
  with_items:
    - /opt/tftpboot
    - /opt/tftpboot/pxelinux.cfg
    - /opt/tftpboot/bootimg
    - /opt/tftpboot/bootimg/memtest
    - /opt/tftpboot/bootimg/fedora/29/x86_64
    - /opt/tftpboot/bootimg/centos/7/x86_64
    - /opt/tftpboot/bootimg/ubuntu/18.04/x86_64
  become: true

- name: fetch ipxe
  get_url:
    url: http://boot.ipxe.org/undionly.kpxe
    dest: /opt/tftpboot/undionly.kpxe

- name: fetch fedora boot images
  get_url:
    url: http://mirrors.kernel.org/fedora/releases/29/Workstation/x86_64/os/isolinux/{{ item }}
    dest: /opt/tftpboot/bootimg/fedora/29/x86_64/{{ item }}
  with_items:
    - initrd.img
    - vmlinuz

- name: fetch centos boot images
  get_url:
    url: http://mirrors.usinternet.com/centos/7/os/x86_64/isolinux/{{ item }}
    dest: /opt/tftpboot/bootimg/centos/7/x86_64/{{ item }}
  with_items:
    - initrd.img
    - vmlinuz

- name: cleanup old netboot
  file:
    path: /tmp/netboot
    state: absent

- name: mkdir /tmp/netboot
  file:
    path: /tmp/netboot
    state: directory

- name: fetch ubuntu boot images
  get_url:
    url: http://archive.ubuntu.com/ubuntu/dists/bionic-updates/main/installer-amd64/current/images/netboot/netboot.tar.gz
    dest: /tmp/netboot/netboot.tar.gz

- name: unpack netboot.tar.gz
  unarchive:
    src: /tmp/netboot/netboot.tar.gz
    dest: /tmp/netboot

- name: copy ubuntu boot images
  copy:
    src: /tmp/netboot/ubuntu-installer/amd64/{{ item }}
    dest: /opt/tftpboot/bootimg/ubuntu/18.04/x86_64/{{ item }}
  with_items:
    - linux
    - initrd.gz

- name: copy syslinux images
  copy:
    src: /usr/share/syslinux/{{ item }}
    dest: /opt/tftpboot/{{ item }}
  with_items:
    - pxelinux.0
    - vesamenu.c32
    - ldlinux.c32
    - libcom32.c32
    - libutil.c32

- name: copy dnsmasq.conf
  copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
  become: true
