---
- name: get latest memtest version
  shell: curl -s -L "http://memtest.org/#downiso" | grep VERSION | awk '{print $3}' | awk -F'<' '{print $1}'
  register: memtest_version
  changed_when: "memtest_version.rc != 0"

- name: show contents
  debug: var=memtest_version

## ansible is dumb when it comes to wildcards so ignore warning
- name: cleanup prev
  shell: rm -f /opt/tftpboot/bootimg/memtest/memtest86*.bin.gz

- name: get memtest
  get_url:
    url: http://www.memtest.org/download/{{ memtest_version.stdout }}/memtest86+-{{ memtest_version.stdout }}.bin.gz
    dest: /opt/tftpboot/bootimg/memtest/memtest86+-{{ memtest_version.stdout }}.bin.gz

- name: unzip memtest
  shell: gunzip memtest86+-{{ memtest_version.stdout }}.bin.gz
  args:
    chdir: /opt/tftpboot/bootimg/memtest

- name: cp memtest
  copy:
    src: /opt/tftpboot/bootimg/memtest/memtest86+-{{ memtest_version.stdout }}.bin
    dest: /opt/tftpboot/bootimg/memtest/memtest
